// Luxury Cake Configuration & Decoration Definitions

export const DECORATION_CATALOG = [
  {
    type: 'candle',
    name: 'Candle',
    shortName: 'Candles',
    maxCount: 5,
    description: 'Slender gold & ivory spiral candle with flickering flame',
  },
  {
    type: 'cake_topper',
    name: '21 Crown',
    shortName: '21 Topper',
    maxCount: 1,
    description: 'Polished mirror gold royal 21 crest topper',
  },
  {
    type: 'pink_rose',
    name: 'Pink Rose',
    shortName: 'Pink Roses',
    maxCount: 2,
    description: 'Blush pink velvet petals with realistic shading',
  },
  {
    type: 'white_rose',
    name: 'White Rose',
    shortName: 'White Roses',
    maxCount: 2,
    description: 'Creamy ivory rose dusted with gold shimmer',
  },
  {
    type: 'gold_heart',
    name: 'Gold Heart',
    shortName: 'Gold Hearts',
    maxCount: 2,
    description: 'Sculpted 3D mirror gold metallic heart',
  },
  {
    type: 'ribbon',
    name: 'Silk Ribbon',
    shortName: 'Satin Ribbon',
    maxCount: 1,
    description: 'Luxury satin bow tied at tier center',
  },
  {
    type: 'butterfly',
    name: 'Butterfly',
    shortName: 'Butterflies',
    maxCount: 2,
    description: 'Translucent wings with gold filigree veins',
  },
  {
    type: 'pearls',
    name: 'Pearl Trim',
    shortName: 'Pearls',
    maxCount: 1,
    description: 'Strand of iridescent edible white pearls at base',
  },
  {
    type: 'small_star',
    name: 'Gold Star',
    shortName: 'Stars',
    maxCount: 3,
    description: 'Sparkling 8-point gold foil star accents',
  },
];

export const TARGET_SLOTS = [
  { id: 'topper_center', type: 'cake_topper', x: 50, y: 13, label: '21 Crown Topper' },
  { id: 'candle_1', type: 'candle', x: 31, y: 23, label: 'Candle 1' },
  { id: 'candle_2', type: 'candle', x: 41, y: 21, label: 'Candle 2' },
  { id: 'candle_3', type: 'candle', x: 50, y: 20, label: 'Candle 3' },
  { id: 'candle_4', type: 'candle', x: 59, y: 21, label: 'Candle 4' },
  { id: 'candle_5', type: 'candle', x: 69, y: 23, label: 'Candle 5' },
  { id: 'top_rose_pink', type: 'pink_rose', x: 34, y: 41, label: 'Pink Rose (Top)' },
  { id: 'top_rose_white', type: 'white_rose', x: 66, y: 41, label: 'White Rose (Top)' },
  { id: 'top_gold_heart', type: 'gold_heart', x: 50, y: 36, label: 'Gold Heart (Top)' },
  { id: 'top_star', type: 'small_star', x: 43, y: 30, label: 'Star (Top)' },
  { id: 'bottom_ribbon', type: 'ribbon', x: 50, y: 62, label: 'Satin Bow (Center)' },
  { id: 'bottom_rose_pink', type: 'pink_rose', x: 27, y: 68, label: 'Pink Rose (Bottom)' },
  { id: 'bottom_rose_white', type: 'white_rose', x: 73, y: 68, label: 'White Rose (Bottom)' },
  { id: 'bottom_gold_heart', type: 'gold_heart', x: 50, y: 77, label: 'Gold Heart (Bottom)' },
  { id: 'butterfly_left', type: 'butterfly', x: 18, y: 57, label: 'Butterfly (Left)' },
  { id: 'butterfly_right', type: 'butterfly', x: 82, y: 57, label: 'Butterfly (Right)' },
  { id: 'pearls_base', type: 'pearls', x: 50, y: 88, label: 'Pearl Trim (Base)' },
  { id: 'bottom_star_1', type: 'small_star', x: 33, y: 55, label: 'Star (Left)' },
  { id: 'bottom_star_2', type: 'small_star', x: 67, y: 55, label: 'Star (Right)' },
];
